name: flutter_aeroform
resolution: workspace
description: "Mobile-first Infrastructure as Code (Aeroform) for cloud provisioning."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.0
  flutter_web_auth_2: ^3.1.2
  crypto: ^3.0.3
  path: ^1.9.1
  uuid: ^4.0.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^10.0.0
  cubit_ui_flow:
    git: 
      url: git@github.com:qtpi-bonding-org/flutter_cubit_ui_flow.git
      ref: 737f24b
  flutter_client_sse: ^2.0.3
  pocketbase: ^0.23.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mocktail: ^1.0.0
